services:
  - type: web
    name: cznumis-fe
    runtime: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    healthCheckPath: /
    autoDeploy: true
