services:
  - type: web
    name: cznumis-fe
    env: static
    buildCommand: yarn install && yarn build && yarn export
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
